apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellowtaxi-app
spec:
  selector:
    matchLabels:
      app: yellowtaxi-app
  template:
    metadata:
      labels:
        app: yellowtaxi-app
    spec:
      containers:
      - name: yellowtaxi-app
        image: comtudux/yellowtaxiakkastat:0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 10001

---

apiVersion: v1
kind: Service
metadata:
  name: yellowtaxi-svc
spec:
  type: LoadBalancer
  selector:
    app: yellowtaxi-app
  ports:
  - port: 10001
    targetPort: 10001   